{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skyflo.postgres.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skyflo.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ include "skyflo.postgres.password" . | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  POSTGRES_PORT: {{ .Values.postgresql.auth.port | quote }}
{{- end }}
