apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skyflo.ui.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skyflo.labels" . | nindent 4 }}
data:
  NEXT_PUBLIC_APP_NAME: {{ .Values.ui.config.appName | quote }}
  NODE_ENV: {{ .Values.ui.config.nodeEnv | quote }}
  NEXT_PUBLIC_ENABLE_ANALYTICS: {{ .Values.ui.config.enableAnalytics | quote }}
  NEXT_PUBLIC_ENABLE_FEEDBACK: {{ .Values.ui.config.enableFeedback | quote }}
  API_URL: {{ include "skyflo.engine.apiUrl" . | quote }}
  NEXT_PUBLIC_API_URL: {{ .Values.ui.config.publicApiUrl | quote }}
