apiVersion: v1
kind: Service
metadata:
  name: {{ include "skyflo.ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skyflo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: 80
      targetPort: http-proxy
      protocol: TCP
      name: http
    - port: 3000
      targetPort: http
      protocol: TCP
      name: ui-http
  selector:
    app: {{ include "skyflo.ui.fullname" . }}
