---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-prod
  namespace: prod
  labels:
    app: api-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-prod
  template:
    metadata:
      labels:
        app: api-prod
    spec:
      containers:
      - name: api-prod
        image: nginx:1.345 # Incorrect image tag
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-prod
  namespace: prod
spec:
  selector:
    app: api-prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
