apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: skyflo-ai
nodes:
- role: control-plane
  image: kindest/node:v1.32.2
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 30081
    hostPort: 30081
    listenAddress: "0.0.0.0"
    protocol: TCP
- role: worker
  image: kindest/node:v1.32.2
